# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

# 레이블
labels:
  'release':
    include:
      - '\bproduction\b'
  'phase':
    include:
      - '\bphase\b'
  'bug':
    include:
      - '\bbugfix\b'
  'test':
    include:
      - '\btest\b'
  'feature':
    include:
      - '\bfeature\b'
  'documentation':
    include:
      - '\bdocs\b'
  'refactor':
    include:
      - '\brefact\b'
  'style':
    include:
      - '\bstyle\b'