name: Are you sure
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["Build Test", "Deploy CI At Vercel"]
    types:
      - completed
jobs:
  auto-merge-check:
    if: contains(github.event.head_commit.message, '/merge plz/')
    runs-on: ubuntu-latest
    steps:
      - name: Approwve PR, Merge bot comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONFLOW_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }},
              event: 'REQUEST_CHANGES',
            })
            
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }},
            })

      - name: 실패시
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.ACTIONFLOW_TOKEN }}
          script: |
            const pull_number = ${{ github.event.pull_request.number }}
            const updated_title = `[TEST FAIL] ${{ github.event.pull_request.title }}`
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              body: '마지막 코멘트가 아닙니다!',
              event: 'REQUEST_CHANGES'
            })

