name: Are you sure
on:
  workflow_run:
    workflows: ["Build Test", "Deploy CI At Vercel"]
    types:
      - completed
jobs:
  auto-merge-check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '/merge plz/') }}
    steps:
      - name: Approwve PR, Merge bot comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ACTIONFLOW_TOKEN }}
          script: |
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }},
              event: 'REQUEST_CHANGES',
            })
            
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }},
            })

