name: run test
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - name: Github commit
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request._links.commits) }}
          GITHUB_COMMIT: ${{ toJson(github.event.head_commit) }}
        run: echo "$GITHUB_COMMIT"

      - name: Dump GitHub context 왜 안돼
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"

